version: '3.6'
services:
  iris-datafest:
    build: 
      context: .
      dockerfile: Dockerfile
    image: iris-datafest
    container_name: iris-datafest
    command: --check-caps false --ISCAgent false
    restart: always
    hostname: iris
    ports:
      - 41773:1972
      - 42773:52773
      - 8080:8080